name: CI Workflow

on:
  pull_request:
    branches:
      - main
    types: [closed]  # Only run when the PR is closed (which includes merges)
  push:
    branches:
      - main  # Also run on direct pushes to the main branch

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'push' }}  # Run only if the PR was merged or it's a push event
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test
